# Generated by Django 2.1.7 on 2019-03-01 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20190222_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='first_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='Myapp.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='second_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='Myapp.Team'),
        ),
    ]
