# Generated by Django 2.1.7 on 2019-03-01 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20190301_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
    ]
