# Generated by Django 2.1.7 on 2019-03-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_auto_20190301_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='first_team',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamescore',
            name='second_team',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='first_team_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='Myapp.Team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='second_team_relation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='Myapp.Team'),
            preserve_default=False,
        ),
    ]
