# Generated by Django 2.1.7 on 2019-03-02 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20190302_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
    ]
